version: 2.1

workflows: 
  testing: 
    jobs: 
      - test
      - ubuntu
jobs:
  test:
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
      - run:         
          name: Install all dependencies
          command: yarn 
      - run: 
          name: Run test
          command: yarn test
      


  ubuntu:
    docker: 
      - image: circleci/node
    steps:
      - checkout
      - run: echo hello world
      - run: whoami
        
