version: 2.1
commands:
  all_command:
    steps:
      - run:         
          name: Install all dependencies
          command: yarn 
      - run: 
          name: Run test
          command: yarn test

workflows: 
  testing: 
    jobs: 
      - test
      - ubuntu:
          requires:
            - test
jobs:
  test:
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
      - all_command
      


  ubuntu:
    docker: 
      - image: circleci/node
    steps:
      - checkout
      - run: echo hello world
      - run: whoami
        
